# Generated by Django 6.0.3 on 2026-03-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='report_type',
            field=models.CharField(choices=[('stage_discharge', 'Stage/Discharge Analysis'), ('groundwater', 'Groundwater Analysis'), ('precipitation', 'Precipitation Analysis')], max_length=50),
        ),
        migrations.CreateModel(
            name='PrecipCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desired_tips', models.PositiveIntegerField()),
                ('actual_tips', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precip_calibrations', to='analysis.analysisreport')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
