# Generated by Django 6.0.3 on 2026-03-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_precipcomparisonsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precipcalibration',
            name='actual_tips',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='precipcalibration',
            name='desired_tips',
            field=models.FloatField(),
        ),
    ]
