# Generated by Django 6.0.3 on 2026-03-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_precipcalibration_actual_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
