# Generated by Django 6.0.3 on 2026-03-26 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_add_is_complete'),
        ('sites', '0003_move_schedule_to_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analysisreport',
            unique_together={('user', 'site', 'period_start', 'period_end')},
        ),
    ]
