# Generated by Django 6.0.3 on 2026-03-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_unique_report_per_user_site_dates'),
        ('usgs_sites', '0003_move_schedule_to_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageQComparisonSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_q_comparison_sites', to='analysis.analysisreport')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usgs_sites.site')),
            ],
            options={
                'ordering': ['site__site_no'],
                'unique_together': {('report', 'site')},
            },
        ),
    ]
