# Generated by Django 6.0.3 on 2026-03-15 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('huc', models.CharField(blank=True, max_length=12, verbose_name='HUC')),
            ],
            options={
                'ordering': ['site_no'],
            },
        ),
        migrations.CreateModel(
            name='NovaPointLocator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_locator', models.CharField(help_text='ALERT or ALERT2 address from the Novastar Point Data Viewer.', max_length=50)),
                ('parameter_type', models.CharField(help_text='Type of measurement (e.g. Stage, Precipitation, Discharge).', max_length=100)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nova_point_locators', to='sites.site')),
            ],
            options={
                'ordering': ['site__site_no', 'parameter_type'],
                'unique_together': {('site', 'point_locator')},
            },
        ),
        migrations.CreateModel(
            name='SiteRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_minutes', models.FloatField(default=0, help_text='Time-of-travel from upstream to downstream site (minutes).')),
                ('offset_type', models.CharField(choices=[('fixed', 'Fixed (minutes)'), ('flow_dependent', 'Flow-dependent (future)')], default='fixed', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_relationships', to=settings.AUTH_USER_MODEL)),
                ('downstream_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_relationships', to='sites.site')),
                ('upstream_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_relationships', to='sites.site')),
            ],
            options={
                'ordering': ['downstream_site__site_no', 'upstream_site__site_no'],
                'unique_together': {('created_by', 'upstream_site', 'downstream_site')},
            },
        ),
    ]
